---
kind: ConfigMap
apiVersion: v1
metadata:
  name: http-status-config-yaml
  labels:
    name: http-status-config-yaml
    chart: http-status
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
