---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name | default "http-status" | lower }}-config-yaml
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Release.Name | default "http-status" | lower }}-config-yaml
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
