---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: http-status-config-yaml
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  selector:
    name: http-status
  ports:
  - port: 80
    targetPort: 80
    name: http
