---
apiVersion: v1
kind: Service
metadata:
  name: http-status
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: http-status-config-yaml
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: http-status
  ports:
  - port: 80
    targetPort: 80
    name: http
