---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default "http-status" | lower | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Release.Name | default "http-status" | lower }}-config-yaml
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: {{ .Release.Name | default "http-status" | lower | quote }}
  ports:
  - port: 80
    targetPort: 80
    name: http
